site_name: Blog de Jose Antonio
site_description: 'Sitio Mkdocs de Jose Antonio Abad Jurado en el que est치n sus pr치cticas de IAW'
site_author: Jose Antonio

nav:
    - Principal: index.md
    - Pr치ctica 1: about.md
    - Pr치ctica 2: practica2.md

theme:
  name: 'material'
  lenguage: 'es'
  palette:
    primary: 'blue grey'
    accent: 'black'
  front:
    text: 'Robot'
    code: 'Roboto Mono'